version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes
permission:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ex2-user
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 3600
      runas: ec2-user